version: "3.0"

services:
  liquidity-contract-connector:
    image: markaurelius/liquidity-contract-connector:latest
    container_name: "liquidity-contract-connector"
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - custom

  liquidity-admin-tgbot:
    image: liquidity-admin
    container_name: "liquidity-contract-tgbot"

    networks:
      - custom
networks:
  custom:
    driver: bridge
